package ga.ui.panels;

import ga.listeners.StepDetails;
import ga.ui.models.StepDetailsTableModel;

/**
 *
 *
 */
public class StepDetailsPanel extends javax.swing.JPanel
{
    private StepDetailsTableModel stepDetailsTableModel;
    
    public StepDetailsPanel()
    {
        initComponents();
        stepDetailsTableModel = new StepDetailsTableModel();
        tableStepDetails.setModel(stepDetailsTableModel);
    }

    public void addStepDetails(StepDetails stepDetails)
    {
        stepDetailsTableModel.addStepDetails(stepDetails);
    }
    
    public void clearStepDetails()
    {
        stepDetailsTableModel.clearStepDetails();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrollPaneStepDetails = new javax.swing.JScrollPane();
        tableStepDetails = new javax.swing.JTable();

        tableStepDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        scrollPaneStepDetails.setViewportView(tableStepDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneStepDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneStepDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPaneStepDetails;
    private javax.swing.JTable tableStepDetails;
    // End of variables declaration//GEN-END:variables
}
